version: "3.8"

services:
  web-api:
    image: web-api
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ALLOW_ORIGINS=http://localhost
    #   - MEDIA_DIRECTORY_PATH=media
    networks:
      - my-network

  web-app:
    image: web-app
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - API_URL=http://web-api:8000
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
      - web-app
    networks:
      - my-network


networks:
  my-network:

